#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using NetSaleSvc.Admin;
    using NetSaleSvc.Admin.Models;
    using NetSaleSvc.Admin.Properties;
    using NetSaleSvc.Entity.Enum;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Error/ErrorDefault.cshtml")]
    public partial class _Views_Error_ErrorDefault_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Error_ErrorDefault_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\Error\ErrorDefault.cshtml"
  
    ViewBag.Title = "错误";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<section");

WriteLiteral(" class=\"content-header\"");

WriteLiteral(">\r\n    <h1>\r\n        出错了~~~\r\n        <small></small>\r\n    </h1>\r\n</section>\r\n\r\n<s" +
"ection");

WriteLiteral(" class=\"content\"");

WriteLiteral(">\r\n    <!-- Your Page Content Here -->\r\n\r\n    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-xs-12\"");

WriteLiteral(">\r\n            <h3>请重试....</h3>\r\n        </div>\r\n    </div>\r\n\r\n</section>\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
