#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using NetSaleSvc.Admin;
    using NetSaleSvc.Admin.Models;
    using NetSaleSvc.Admin.Properties;
    using NetSaleSvc.Entity.Enum;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Order/Index.cshtml")]
    public partial class _Views_Order_Index_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Order_Index_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 2 "..\..\Views\Order\Index.cshtml"
  
    ViewBag.Order = "active";
    ViewBag.Title = "订单管理";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<!-- Content Header (Page header) -->\r\n<section");

WriteLiteral(" class=\"content-header\"");

WriteLiteral(">\r\n    <h1>\r\n        订单管理\r\n        <small>查看并管理订单</small>\r\n    </h1>\r\n    <ol");

WriteLiteral(" class=\"breadcrumb\"");

WriteLiteral(">\r\n        <li><a");

WriteLiteral(" href=\"javascript:;\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-file-text-o\"");

WriteLiteral("></i> 订单管理</a></li>\r\n        <li");

WriteLiteral(" class=\"active\"");

WriteLiteral(">订单管理</li>\r\n    </ol>\r\n</section>\r\n\r\n<!-- Main content -->\r\n<section");

WriteLiteral(" class=\"content\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"dataTables_wrapper table-responsive no-padding\"");

WriteLiteral(">\r\n                <table");

WriteLiteral(" id=\"DataTable\"");

WriteLiteral(" class=\"table table-bordered-edge table-hover dataTable\"");

WriteLiteral("\r\n                       data-toggle=\"dynatable-paged\"");

WriteLiteral("\r\n                       data-url=\"");

            
            #line 26 "..\..\Views\Order\Index.cshtml"
                            Write(Url.Action(MvcNames.Order.List));

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral("\r\n                       data-row-template=\"order-row-template\"");

WriteLiteral(">\r\n                    <thead>\r\n                        <tr>\r\n                   " +
"         <th");

WriteLiteral(" data-dynatable-no-sort=\"true\"");

WriteLiteral(">#</th>\r\n                            <th");

WriteLiteral(" data-dynatable-no-sort=\"true\"");

WriteLiteral(">影院名称</th>\r\n                            <th");

WriteLiteral(" data-dynatable-no-sort=\"true\"");

WriteLiteral(">影片名称</th>\r\n                            <th");

WriteLiteral(" data-dynatable-no-sort=\"true\"");

WriteLiteral(">放映时间</th>\r\n                            <th");

WriteLiteral(" data-dynatable-no-sort=\"true\"");

WriteLiteral(">张数</th>\r\n                            <th");

WriteLiteral(" data-dynatable-no-sort=\"true\"");

WriteLiteral(">总金额</th>\r\n                            <th");

WriteLiteral(" data-dynatable-no-sort=\"true\"");

WriteLiteral(">总服务费</th>\r\n                            <th");

WriteLiteral(" data-dynatable-no-sort=\"true\"");

WriteLiteral(">渠道</th>\r\n                            <th");

WriteLiteral(" data-dynatable-no-sort=\"true\"");

WriteLiteral(">订单号</th>\r\n                            <th");

WriteLiteral(" data-dynatable-no-sort=\"true\"");

WriteLiteral(">订单时间</th>\r\n                            <th");

WriteLiteral(" data-dynatable-no-sort=\"true\"");

WriteLiteral(">手机号码</th>\r\n                            <th");

WriteLiteral(" data-dynatable-no-sort=\"true\"");

WriteLiteral(">状态</th>\r\n                            <th");

WriteLiteral(" data-dynatable-no-sort=\"true\"");

WriteLiteral(">操作</th>\r\n                        </tr>\r\n                    </thead>\r\n          " +
"          <tbody></tbody>\r\n                </table>\r\n                <div");

WriteLiteral(" class=\"dynatable-custom-filter\"");

WriteLiteral(">\r\n                    <div>\r\n");

WriteLiteral("                        ");

            
            #line 49 "..\..\Views\Order\Index.cshtml"
                   Write(Html.DropDownList("ThirdUserId", null, "渠道", new { style = "width:175px;", @class = "dynatable-query", data_toggle = "select2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                        ");

            
            #line 50 "..\..\Views\Order\Index.cshtml"
                   Write(Html.DropDownList("OrderStatus", null, "订单状态", new { style = "width:175px;", @class = "dynatable-query", data_toggle = "select2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" placeholder=\"订单时间\"");

WriteLiteral(" name=\"OrderDateRange\"");

WriteLiteral(" style=\"display:inline-block;width:195px;font-size:14px;height:34px;margin-left:5" +
"px;\"");

WriteLiteral(" class=\"form-control dynatable-query js-date-range\"");

WriteLiteral(" />\r\n                    </div>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"dynatable-operation\"");

WriteLiteral(">\r\n                    <a");

WriteLiteral(" class=\"btn btn-success btn-sm\"");

WriteLiteral(" href=\"javascript:;\"");

WriteLiteral(">\r\n                        <i");

WriteLiteral(" class=\"fa fa-download\"");

WriteLiteral("></i>\r\n                        导出\r\n                    </a>\r\n                </di" +
"v>\r\n            </div>\r\n\r\n            <script");

WriteLiteral(" type=\"text/x-handlebars-template\"");

WriteLiteral(" id=\"order-row-template\"");

WriteLiteral(@">
                <tr>
                    <td style=""text-align: left;"">{{row}}</td>
                    <td style=""text-align: left; "">{{cinemaName}}</td>
                    <td style=""text-align: left;"">{{filmName}}</td>
                    <td style=""text-align: left;"">{{sessionTime}}</td>
                    <td style=""text-align: left;"">{{ticketCount}}</td>
                    <td style=""text-align: left;"">{{price}}</td>
                    <td style=""text-align: left;"">{{fee}}</td>
                    <td style=""text-align: left;"">{{thirdUserName}}</td>
                    <td style=""text-align: left;"">{{orderCode}}</td>
                    <td style=""text-align: left;"">{{orderTime}}</td>
                    <td style=""text-align: left;"">{{mobile}}</td>
                    <td style=""text-align: left; color:{{statusClass}}"">{{orderStatus}}</td>
                    <td style=""text-align: left;"">
                        详情
                    </td>
                </tr>
            </script>
        </div>
    </div>
</section>

");

DefineSection("scripts", () => {

WriteLiteral("\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">
        $('.js-date-range').daterangepicker({
            ""locale"": App.dateRangePickerLocal,
            'autoUpdateInput': false
        }).on('cancel.daterangepicker', function () {
            $(this).val(null).trigger('change')
        }).on('apply.daterangepicker', function (ev, picker) {
            $(this).val(picker.startDate.format('MM/DD/YYYY') + ' - ' + picker.endDate.format('MM/DD/YYYY')).trigger('change')
        })
    </script>
");

});

        }
    }
}
#pragma warning restore 1591
