#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using NetSaleSvc.Admin;
    using NetSaleSvc.Admin.Models;
    using NetSaleSvc.Admin.Properties;
    using NetSaleSvc.Entity.Enum;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Login/Index.cshtml")]
    public partial class _Views_Login_Index_cshtml : System.Web.Mvc.WebViewPage<SysUserLoginViewModel>
    {
        public _Views_Login_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Views\Login\Index.cshtml"
  
    Layout = null;

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<!DOCTYPE html>\r\n<html>\r\n<head>\r\n    <meta");

WriteLiteral(" charset=\"utf-8\"");

WriteLiteral(">\r\n    <meta");

WriteLiteral(" http-equiv=\"X-UA-Compatible\"");

WriteLiteral(" content=\"IE=edge\"");

WriteLiteral(">\r\n    <title>普照电商云平台</title>\r\n    <!-- Tell the browser to be responsive to scre" +
"en width -->\r\n    <meta");

WriteLiteral(" content=\"width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no\"" +
"");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(">\r\n    <!-- Bootstrap 3.3.6 -->\r\n    <link");

WriteLiteral(" href=\"https://staticfile.qnssl.com/twitter-bootstrap/3.3.5/css/bootstrap.min.css" +
"\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <!-- Theme style -->\r\n");

WriteLiteral("    ");

            
            #line 17 "..\..\Views\Login\Index.cshtml"
Write(Styles.Render(Resources.ADMINLTE_STYLE));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 606), Tuple.Create("\"", 636)
, Tuple.Create(Tuple.Create("", 613), Tuple.Create<System.Object, System.Int32>(Href("~/Content/css/login.css")
, 613), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n</head>\r\n<body");

WriteLiteral(" class=\"hold-transition login-page bkgImg\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"login-box\"");

WriteLiteral(">\r\n        <!-- /.login-logo -->\r\n        <div");

WriteLiteral(" class=\"login-box-body login-box-body-extra\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"login-box-msg\"");

WriteLiteral(">\r\n                <img");

WriteAttribute("src", Tuple.Create(" src=\"", 898), Tuple.Create("\"", 928)
, Tuple.Create(Tuple.Create("", 904), Tuple.Create<System.Object, System.Int32>(Href("~/Content/img/Avator.png")
, 904), false)
);

WriteLiteral(" class=\"enter_img\"");

WriteLiteral(">\r\n            </div>\r\n\r\n");

            
            #line 29 "..\..\Views\Login\Index.cshtml"
            
            
            #line default
            #line hidden
            
            #line 29 "..\..\Views\Login\Index.cshtml"
             using (Html.BeginForm(null, null, new { returnUrl = Request.QueryString["returnUrl"] }, FormMethod.Post))
            {

            
            #line default
            #line hidden
WriteLiteral("                <div");

WriteLiteral(" class=\"form-group has-feedback\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 32 "..\..\Views\Login\Index.cshtml"
               Write(Html.TextBoxFor(x => x.Username, new { @class = "form-control", placeholder = "用户名" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <span");

WriteLiteral(" class=\"glyphicon glyphicon-user form-control-feedback\"");

WriteLiteral("></span>\r\n");

WriteLiteral("                    ");

            
            #line 34 "..\..\Views\Login\Index.cshtml"
               Write(Html.ValidationMessageFor(x => x.Username, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n");

WriteLiteral("                <div");

WriteLiteral(" class=\"form-group has-feedback\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 37 "..\..\Views\Login\Index.cshtml"
               Write(Html.PasswordFor(x => x.Password, new { @class = "form-control", placeholder = "密码" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <span");

WriteLiteral(" class=\"glyphicon glyphicon-lock form-control-feedback\"");

WriteLiteral("></span>\r\n");

WriteLiteral("                    ");

            
            #line 39 "..\..\Views\Login\Index.cshtml"
               Write(Html.ValidationMessageFor(x => x.Password, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n");

            
            #line 41 "..\..\Views\Login\Index.cshtml"

                
            
            #line default
            #line hidden
            
            #line 42 "..\..\Views\Login\Index.cshtml"
           Write(Html.ValidationSummary(true, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
            
            #line 42 "..\..\Views\Login\Index.cshtml"
                                                                                 


            
            #line default
            #line hidden
WriteLiteral("                <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                    <!-- /.col -->\r\n                    <div");

WriteLiteral(" class=\"col-xs-12\"");

WriteLiteral(">\r\n                        <button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn btn-primary btn-block btn-flat\"");

WriteLiteral(">登陆</button>\r\n                    </div>\r\n                    <!-- /.col -->\r\n   " +
"             </div>\r\n");

            
            #line 51 "..\..\Views\Login\Index.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </div>\r\n        <!-- /.login-box-body -->\r\n    </div>\r\n    <!-- /.login-b" +
"ox -->\r\n    <!-- jQuery -->\r\n");

WriteLiteral("    ");

            
            #line 57 "..\..\Views\Login\Index.cshtml"
Write(Scripts.Render(Resources.JQUERY));

            
            #line default
            #line hidden
WriteLiteral("\r\n</body>\r\n</html>\r\n");

        }
    }
}
#pragma warning restore 1591
