#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using NetSaleSvc.Admin;
    using NetSaleSvc.Admin.Models;
    using NetSaleSvc.Admin.Properties;
    using NetSaleSvc.Entity.Enum;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Role/CreateOrUpdate.cshtml")]
    public partial class _Views_Role_CreateOrUpdate_cshtml : System.Web.Mvc.WebViewPage<CreateOrUpdateRoleViewModel>
    {
        public _Views_Role_CreateOrUpdate_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Views\Role\CreateOrUpdate.cshtml"
  
    ViewBag.System = "active";
    ViewBag.Role = "active";
    ViewBag.Title = Model.Id > 0 ? "角色编辑" : "角色添加";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<!-- Content Header (Page header) -->\r\n<section");

WriteLiteral(" class=\"content-header\"");

WriteLiteral(">\r\n    <h1>\r\n");

WriteLiteral("        ");

            
            #line 11 "..\..\Views\Role\CreateOrUpdate.cshtml"
    Write(Model.Id > 0 ? "角色编辑" : "角色添加");

            
            #line default
            #line hidden
WriteLiteral("\r\n        <small>角色管理</small>\r\n    </h1>\r\n    <ol");

WriteLiteral(" class=\"breadcrumb\"");

WriteLiteral(">\r\n        <li><a");

WriteLiteral(" href=\"javascript:;\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-cog\"");

WriteLiteral("></i> 系统管理</a></li>\r\n        <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 445), Tuple.Create("\"", 484)
            
            #line 16 "..\..\Views\Role\CreateOrUpdate.cshtml"
, Tuple.Create(Tuple.Create("", 452), Tuple.Create<System.Object, System.Int32>(Url.Action(MvcNames.Role.Index)
            
            #line default
            #line hidden
, 452), false)
);

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-group\"");

WriteLiteral("></i> 角色管理</a></li>\r\n        <li");

WriteLiteral(" class=\"active\"");

WriteLiteral(">");

            
            #line 17 "..\..\Views\Role\CreateOrUpdate.cshtml"
                       Write(Model.Id > 0 ? "角色编辑" : "角色添加");

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n    </ol>\r\n</section>\r\n\r\n");

            
            #line 21 "..\..\Views\Role\CreateOrUpdate.cshtml"
 using (Ajax.BeginForm(MvcNames.Role._CreateOrUpdate, null, null, new AjaxOptions
    {
        HttpMethod = "POST",
        OnSuccess = "App.onOperationSuccessSimple",
        OnBegin = "App.onFormCommitBegin",
        OnComplete = "App.onFormCommitComplete"
    }, new { @class = "form-horizontal" }))
{

            
            #line default
            #line hidden
WriteLiteral("    <!-- Main content -->\r\n");

WriteLiteral("    <section");

WriteLiteral(" class=\"content\"");

WriteLiteral(">\r\n        <!-- Your Page Content Here -->\r\n\r\n        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-xs-12\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"box box-default\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"box-header with-border\"");

WriteLiteral(">\r\n                        <h3");

WriteLiteral(" class=\"box-title\"");

WriteLiteral(">基础信息</h3>\r\n                    </div>\r\n                    <div");

WriteLiteral(" class=\"modal-body\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 40 "..\..\Views\Role\CreateOrUpdate.cshtml"
                   Write(Html.EditorFor(x => x.Id));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                        ");

            
            #line 41 "..\..\Views\Role\CreateOrUpdate.cshtml"
                   Write(Html.EditorFor(x => x.Name));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                        ");

            
            #line 42 "..\..\Views\Role\CreateOrUpdate.cshtml"
                   Write(Html.EditorFor(x => x.Description));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"box box-default\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"box-header with-border\"");

WriteLiteral(">\r\n                        <h3");

WriteLiteral(" class=\"box-title\"");

WriteLiteral(">权限信息</h3>\r\n                    </div>\r\n                    <div");

WriteLiteral(" class=\"modal-body\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 50 "..\..\Views\Role\CreateOrUpdate.cshtml"
                   Write(Html.EditorFor(x => x.Permissions));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                </div>\r\n                <fieldset>\r" +
"\n                    <button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn btn-primary col-xs-2 col-xs-offset-3\"");

WriteLiteral(">保存</button>\r\n                    <a");

WriteLiteral(" class=\"btn btn-default col-xs-2 col-xs-offset-1\"");

WriteAttribute("href", Tuple.Create(" href=\"", 2107), Tuple.Create("\"", 2146)
            
            #line 55 "..\..\Views\Role\CreateOrUpdate.cshtml"
, Tuple.Create(Tuple.Create("", 2114), Tuple.Create<System.Object, System.Int32>(Url.Action(MvcNames.Role.Index)
            
            #line default
            #line hidden
, 2114), false)
);

WriteLiteral(">取消</a>\r\n                </fieldset>\r\n            </div>\r\n        </div>\r\n    </s" +
"ection>\r\n");

            
            #line 60 "..\..\Views\Role\CreateOrUpdate.cshtml"
}
            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
