#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using NetSaleSvc.Admin;
    using NetSaleSvc.Admin.Models;
    using NetSaleSvc.Admin.Properties;
    using NetSaleSvc.Entity.Enum;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/User/ChangePassword.cshtml")]
    public partial class _Views_User_ChangePassword_cshtml : System.Web.Mvc.WebViewPage<ChangePasswordViewModel>
    {
        public _Views_User_ChangePassword_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Views\User\ChangePassword.cshtml"
  
    Layout = null;

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" class=\"modal\"");

WriteLiteral(" tabindex=\"-1\"");

WriteLiteral(" role=\"dialog\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"modal-dialog\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"modal-content\"");

WriteLiteral(">\r\n");

            
            #line 9 "..\..\Views\User\ChangePassword.cshtml"
            
            
            #line default
            #line hidden
            
            #line 9 "..\..\Views\User\ChangePassword.cshtml"
             using (Ajax.BeginForm(null, null,
                new AjaxOptions
                {
                    HttpMethod = "POST",
                    OnSuccess = "App.OnModalSubmitSuccess"
                }, 
                new { @class = "form-horizontal" }))
            {

            
            #line default
            #line hidden
WriteLiteral("                <div");

WriteLiteral(" class=\"modal-header\"");

WriteLiteral(">\r\n                    <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"close\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(" aria-label=\"Close\"");

WriteLiteral("><span");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">&times;</span></button>\r\n                    <h4");

WriteLiteral(" class=\"modal-title\"");

WriteLiteral(" id=\"myModalLabel\"");

WriteLiteral(">修改密码</h4>\r\n                </div>\r\n");

            
            #line 21 "..\..\Views\User\ChangePassword.cshtml"


            
            #line default
            #line hidden
WriteLiteral("                <div");

WriteLiteral(" class=\"modal-body\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 23 "..\..\Views\User\ChangePassword.cshtml"
               Write(Html.EditorFor(x => x.OldPassword));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 24 "..\..\Views\User\ChangePassword.cshtml"
               Write(Html.EditorFor(x => x.NewPassword));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 25 "..\..\Views\User\ChangePassword.cshtml"
               Write(Html.EditorFor(x => x.ConfirmNewPassword));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n");

            
            #line 27 "..\..\Views\User\ChangePassword.cshtml"


            
            #line default
            #line hidden
WriteLiteral("                <div");

WriteLiteral(" class=\"modal-footer\"");

WriteLiteral(">\r\n                    <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-default\"");

WriteLiteral(" style=\"padding: 4px 26px;\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(">关闭</button>\r\n                    <button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn btn-primary\"");

WriteLiteral(" style=\"padding: 4px 26px;\"");

WriteLiteral(">保存</button>\r\n                </div>\r\n");

            
            #line 32 "..\..\Views\User\ChangePassword.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </div>\r\n    </div>\r\n</div>");

        }
    }
}
#pragma warning restore 1591
