#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using NetSaleSvc.Admin;
    using NetSaleSvc.Admin.Models;
    using NetSaleSvc.Admin.Properties;
    using NetSaleSvc.Entity.Enum;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/EditorTemplates/ListBox.cshtml")]
    public partial class _Views_Shared_EditorTemplates_ListBox_cshtml_ : System.Web.Mvc.WebViewPage<object>
    {
        public _Views_Shared_EditorTemplates_ListBox_cshtml_()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Shared\EditorTemplates\ListBox.cshtml"
  
    var selectList = ViewData[ViewData.ModelMetadata.PropertyName + ViewData.ModelMetadata.AdditionalValues["Suffix"]] as IEnumerable<SelectListItem>;
    var multiple = Convert.ToBoolean(ViewData.ModelMetadata.AdditionalValues["Multiple"]);
    var checkboxListStyle = Convert.ToBoolean(ViewData.ModelMetadata.AdditionalValues["CheckBoxListStyle"]);
    if (Model != null)
    {
        if (multiple)
        {
            var vList = new List<string>();
            var intList = Model as IList<int>;
            if (intList != null)
            {
                vList.AddRange(intList.Select(x => x.ToString()));
            }
            else
            {
                vList = Model as List<string>;
            }

            selectList = selectList.Select(x => new SelectListItem
            {
                Text = x.Text,
                Value = x.Value,
                Selected = vList.Any(v => v.Equals(x.Value, StringComparison.Ordinal))
            });
        }
        else
        {
            selectList = selectList.Select(x => new SelectListItem
            {
                Text = x.Text,
                Value = x.Value,
                Selected = x.Value.Equals(Model.ToString(), StringComparison.Ordinal)
            });
        }
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("    ");

            
            #line 42 "..\..\Views\Shared\EditorTemplates\ListBox.cshtml"
Write(Html.LabelFor(x => x, new { @class = "col-sm-3 control-label " + (ViewData.ModelMetadata.IsRequired ? "required" : null) }));

            
            #line default
            #line hidden
WriteLiteral("\r\n    <div");

WriteLiteral(" class=\"col-sm-7\"");

WriteLiteral(">\r\n");

            
            #line 44 "..\..\Views\Shared\EditorTemplates\ListBox.cshtml"
        
            
            #line default
            #line hidden
            
            #line 44 "..\..\Views\Shared\EditorTemplates\ListBox.cshtml"
         if (multiple)
        {
            if (checkboxListStyle)
            {
                var items = selectList.ToArray();
                for (var i = 0; i < items.Length; i++)
                {
                    var item = items[i];

            
            #line default
            #line hidden
WriteLiteral("                    <label");

WriteLiteral(" class=\"checkbox-inline\"");

WriteLiteral(">\r\n                        <input");

WriteAttribute("name", Tuple.Create(" name=\"", 1850), Tuple.Create("\"", 1893)
            
            #line 53 "..\..\Views\Shared\EditorTemplates\ListBox.cshtml"
, Tuple.Create(Tuple.Create("", 1857), Tuple.Create<System.Object, System.Int32>(ViewData.ModelMetadata.PropertyName
            
            #line default
            #line hidden
, 1857), false)
);

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" ");

            
            #line 53 "..\..\Views\Shared\EditorTemplates\ListBox.cshtml"
                                                                                       Write(item.Selected ? "checked" : null);

            
            #line default
            #line hidden
WriteLiteral(" value=\"");

            
            #line 53 "..\..\Views\Shared\EditorTemplates\ListBox.cshtml"
                                                                                                                                 Write(item.Value);

            
            #line default
            #line hidden
WriteLiteral("\" />");

            
            #line 53 "..\..\Views\Shared\EditorTemplates\ListBox.cshtml"
                                                                                                                                                Write(item.Text);

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </label>\r\n");

            
            #line 55 "..\..\Views\Shared\EditorTemplates\ListBox.cshtml"

                    if (i > 0 && items.Length > 10 && (i % 8 == 0))
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <br />\r\n");

            
            #line 59 "..\..\Views\Shared\EditorTemplates\ListBox.cshtml"
                    }
                }
            }
            else
            {
                
            
            #line default
            #line hidden
            
            #line 64 "..\..\Views\Shared\EditorTemplates\ListBox.cshtml"
           Write(Html.ListBoxFor(x => x, selectList, new { @class = "form-control", data_toggle = "select2" }));

            
            #line default
            #line hidden
            
            #line 64 "..\..\Views\Shared\EditorTemplates\ListBox.cshtml"
                                                                                                              
            }
        }
        else
        {
            
            
            #line default
            #line hidden
            
            #line 69 "..\..\Views\Shared\EditorTemplates\ListBox.cshtml"
       Write(Html.DropDownListFor(x => x, selectList, "请选择...", new { @class = "form-control", data_toggle = "select2_" }));

            
            #line default
            #line hidden
            
            #line 69 "..\..\Views\Shared\EditorTemplates\ListBox.cshtml"
                                                                                                                          
        }

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 72 "..\..\Views\Shared\EditorTemplates\ListBox.cshtml"
   Write(Html.ValidationMessageFor(x => x, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n</div>\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
