#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using NetSaleSvc.Admin;
    using NetSaleSvc.Admin.Models;
    using NetSaleSvc.Admin.Properties;
    using NetSaleSvc.Entity.Enum;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/EditorTemplates/String.cshtml")]
    public partial class _Views_Shared_EditorTemplates_String_cshtml_ : System.Web.Mvc.WebViewPage<object>
    {
        public _Views_Shared_EditorTemplates_String_cshtml_()
        {
        }
        public override void Execute()
        {
WriteLiteral("<div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("    ");

            
            #line 4 "..\..\Views\Shared\EditorTemplates\String.cshtml"
Write(Html.LabelFor(x => x, new { @class = "control-label col-sm-3" + " " + (ViewData.ModelMetadata.IsRequired ? "required" : null) }));

            
            #line default
            #line hidden
WriteLiteral("\r\n    <div");

WriteLiteral(" class=\"col-sm-7\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 6 "..\..\Views\Shared\EditorTemplates\String.cshtml"
   Write(Html.TextBoxFor(x => x, htmlAttributes: new { @class = "form-control" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 7 "..\..\Views\Shared\EditorTemplates\String.cshtml"
   Write(Html.ValidationMessageFor(x => x, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 8 "..\..\Views\Shared\EditorTemplates\String.cshtml"
        
            
            #line default
            #line hidden
            
            #line 8 "..\..\Views\Shared\EditorTemplates\String.cshtml"
         if (!string.IsNullOrEmpty(ViewData.ModelMetadata.Description))
        {

            
            #line default
            #line hidden
WriteLiteral("            <span");

WriteLiteral(" class=\"help-block\"");

WriteLiteral(">");

            
            #line 10 "..\..\Views\Shared\EditorTemplates\String.cshtml"
                                Write(ViewData.ModelMetadata.Description);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n");

            
            #line 11 "..\..\Views\Shared\EditorTemplates\String.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </div>\r\n</div>\r\n");

        }
    }
}
#pragma warning restore 1591
