#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using NetSaleSvc.Admin;
    using NetSaleSvc.Admin.Models;
    using NetSaleSvc.Admin.Properties;
    using NetSaleSvc.Entity.Enum;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/EditorTemplates/TextArea.cshtml")]
    public partial class _Views_Shared_EditorTemplates_TextArea_cshtml_ : System.Web.Mvc.WebViewPage<object>
    {
        public _Views_Shared_EditorTemplates_TextArea_cshtml_()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 4 "..\..\Views\Shared\EditorTemplates\TextArea.cshtml"
 if (ViewData.ModelMetadata.HideSurroundingHtml)
{
    if (Convert.ToBoolean(ViewData.ModelMetadata.AdditionalValues["IsEditor"]))
    {
        
            
            #line default
            #line hidden
            
            #line 8 "..\..\Views\Shared\EditorTemplates\TextArea.cshtml"
   Write(Html.TextAreaFor(x => x, new { rows = ViewData.ModelMetadata.AdditionalValues["Rows"], data_toggle = "umeditor", data_height = "280", @class = "width-100" }));

            
            #line default
            #line hidden
            
            #line 8 "..\..\Views\Shared\EditorTemplates\TextArea.cshtml"
                                                                                                                                                                      
    }
    else
    {
        
            
            #line default
            #line hidden
            
            #line 12 "..\..\Views\Shared\EditorTemplates\TextArea.cshtml"
   Write(Html.TextAreaFor(x => x, new { rows = ViewData.ModelMetadata.AdditionalValues["Rows"], cols = ViewData.ModelMetadata.AdditionalValues["Cols"], @class = "form-control" }));

            
            #line default
            #line hidden
            
            #line 12 "..\..\Views\Shared\EditorTemplates\TextArea.cshtml"
                                                                                                                                                                                  
    }
}
else
{

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 18 "..\..\Views\Shared\EditorTemplates\TextArea.cshtml"
   Write(Html.LabelFor(x => x, new { @class = "col-sm-3 control-label " + (ViewData.ModelMetadata.IsRequired ? "required" : null) }));

            
            #line default
            #line hidden
WriteLiteral("\r\n        <div");

WriteLiteral(" class=\"col-sm-7\"");

WriteLiteral(">\r\n");

            
            #line 20 "..\..\Views\Shared\EditorTemplates\TextArea.cshtml"
            
            
            #line default
            #line hidden
            
            #line 20 "..\..\Views\Shared\EditorTemplates\TextArea.cshtml"
             if (Convert.ToBoolean(ViewData.ModelMetadata.AdditionalValues["IsEditor"]))
            {
                
            
            #line default
            #line hidden
            
            #line 22 "..\..\Views\Shared\EditorTemplates\TextArea.cshtml"
           Write(Html.TextAreaFor(x => x, new { rows = ViewData.ModelMetadata.AdditionalValues["Rows"], data_toggle = "umeditor", data_height = "280", @class = "width-100" }));

            
            #line default
            #line hidden
            
            #line 22 "..\..\Views\Shared\EditorTemplates\TextArea.cshtml"
                                                                                                                                                                              
            }
            else
            {
                
            
            #line default
            #line hidden
            
            #line 26 "..\..\Views\Shared\EditorTemplates\TextArea.cshtml"
           Write(Html.TextAreaFor(x => x, new { rows = ViewData.ModelMetadata.AdditionalValues["Rows"], cols = ViewData.ModelMetadata.AdditionalValues["Cols"], @class = "form-control" }));

            
            #line default
            #line hidden
            
            #line 26 "..\..\Views\Shared\EditorTemplates\TextArea.cshtml"
                                                                                                                                                                                          
            }

            
            #line default
            #line hidden
WriteLiteral("            ");

            
            #line 28 "..\..\Views\Shared\EditorTemplates\TextArea.cshtml"
       Write(Html.ValidationMessageFor(x => x, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n    </div>\r\n");

            
            #line 31 "..\..\Views\Shared\EditorTemplates\TextArea.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("\r\n");

        }
    }
}
#pragma warning restore 1591
