#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using NetSaleSvc.Admin;
    using NetSaleSvc.Admin.Models;
    using NetSaleSvc.Admin.Properties;
    using NetSaleSvc.Entity.Enum;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_Layout.cshtml")]
    public partial class _Views_Shared__Layout_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared__Layout_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<!DOCTYPE html>\r\n<html>\r\n<head>\r\n    <meta");

WriteLiteral(" charset=\"utf-8\"");

WriteLiteral(">\r\n    <meta");

WriteLiteral(" http-equiv=\"X-UA-Compatible\"");

WriteLiteral(" content=\"IE=edge\"");

WriteLiteral(">\r\n    <title>");

            
            #line 6 "..\..\Views\Shared\_Layout.cshtml"
      Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral("</title>\r\n    <!-- Tell the browser to be responsive to screen width -->\r\n    <me" +
"ta");

WriteLiteral(" content=\"width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no\"" +
"");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(">\r\n    <!-- Bootstrap 3.3.6 -->\r\n    <link");

WriteLiteral(" href=\"https://staticfile.qnssl.com/twitter-bootstrap/3.3.5/css/bootstrap.min.css" +
"\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <!-- Font Awesome -->\r\n    <link");

WriteLiteral(" href=\"https://staticfile.qnssl.com/font-awesome/4.4.0/css/font-awesome.min.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <!-- 后台公共css -->\r\n");

WriteLiteral("    ");

            
            #line 14 "..\..\Views\Shared\_Layout.cshtml"
Write(Styles.Render(Resources.ADMIN_STYLE));

            
            #line default
            #line hidden
WriteLiteral(@"
    
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src=""https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js""></script>
    <script src=""https://oss.maxcdn.com/respond/1.4.2/respond.min.js""></script>
    <![endif]-->

");

WriteLiteral("    ");

            
            #line 23 "..\..\Views\Shared\_Layout.cshtml"
Write(RenderSection("styles", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n</head>\r\n<body");

WriteLiteral(" class=\"hold-transition skin-blue sidebar-mini\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"wrapper\"");

WriteLiteral(">\r\n        <header");

WriteLiteral(" class=\"main-header\"");

WriteLiteral(">\r\n            <!-- Logo -->\r\n            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 1264), Tuple.Create("\"", 1323)
            
            #line 29 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 1271), Tuple.Create<System.Object, System.Int32>(Url.Action(MvcNames.Home.Index, MvcNames.Home.Name)
            
            #line default
            #line hidden
, 1271), false)
);

WriteLiteral(" class=\"logo\"");

WriteLiteral(">\r\n                <!-- mini logo for sidebar mini 50x50 pixels -->\r\n            " +
"    <span");

WriteLiteral(" class=\"logo-mini\"");

WriteLiteral("><b>80</b>票</span>\r\n                <!-- logo for regular state and mobile device" +
"s -->\r\n                <span");

WriteLiteral(" class=\"logo-lg\"");

WriteLiteral("><b>普照电商</b>云平台</span>\r\n            </a>\r\n            <!-- Header Navbar: style c" +
"an be found in header.less -->\r\n            <nav");

WriteLiteral(" class=\"navbar navbar-static-top\"");

WriteLiteral(">\r\n                <!-- Sidebar toggle button-->\r\n                <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"sidebar-toggle\"");

WriteLiteral(" data-toggle=\"offcanvas\"");

WriteLiteral(" role=\"button\"");

WriteLiteral(">\r\n                    <span");

WriteLiteral(" class=\"sr-only\"");

WriteLiteral(">Toggle navigation</span>\r\n                </a>\r\n                <div");

WriteLiteral(" class=\"navbar-custom-menu\"");

WriteLiteral(">\r\n                    <ul");

WriteLiteral(" class=\"nav navbar-nav\"");

WriteLiteral(">\r\n                        <!-- User Account: style can be found in dropdown.less" +
" -->\r\n                        <li");

WriteLiteral(" class=\"user user-menu\"");

WriteLiteral(">\r\n                            <a");

WriteLiteral(" href=\"javascript:;\"");

WriteLiteral(" class=\"dropdown-toggle\"");

WriteLiteral(">\r\n                                <span");

WriteLiteral(" class=\"hidden-xs\"");

WriteLiteral(">");

            
            #line 46 "..\..\Views\Shared\_Layout.cshtml"
                                                   Write(ViewBag.SysUserName);

            
            #line default
            #line hidden
WriteLiteral("，欢迎您</span>\r\n                            </a>\r\n                        </li>\r\n   " +
"                     <li>\r\n                            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 2490), Tuple.Create("\"", 2558)
            
            #line 50 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 2497), Tuple.Create<System.Object, System.Int32>(Url.Action(MvcNames.User.ChangePassword, MvcNames.User.Name)
            
            #line default
            #line hidden
, 2497), false)
);

WriteLiteral(" data-toggle=\"modal-form\"");

WriteLiteral(">\r\n                                <i");

WriteLiteral(" class=\"fa fa-user-secret\"");

WriteLiteral("></i>\r\n                                修改密码\r\n                            </a>\r\n  " +
"                      </li>\r\n                        <li>\r\n                     " +
"       <a");

WriteAttribute("href", Tuple.Create(" href=\"", 2817), Tuple.Create("\"", 2879)
            
            #line 56 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 2824), Tuple.Create<System.Object, System.Int32>(Url.Action(MvcNames.Login.LogOut, MvcNames.Login.Name)
            
            #line default
            #line hidden
, 2824), false)
);

WriteLiteral(">\r\n                                <i");

WriteLiteral(" class=\"fa fa-sign-out\"");

WriteLiteral(@"></i>
                                登出
                            </a>
                        </li>
                    </ul>
                </div>
            </nav>
        </header>
        <!-- Left side column. contains the logo and sidebar -->
");

WriteLiteral("        ");

            
            #line 66 "..\..\Views\Shared\_Layout.cshtml"
   Write(Html.Partial("_SideBar"));

            
            #line default
            #line hidden
WriteLiteral("\r\n        <!-- Content Wrapper. Contains page content -->\r\n        <div");

WriteLiteral(" class=\"content-wrapper\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 69 "..\..\Views\Shared\_Layout.cshtml"
       Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n        <!-- /.content-wrapper -->\r\n        <footer");

WriteLiteral(" class=\"main-footer\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"pull-right hidden-xs\"");

WriteLiteral(">\r\n                <b></b>\r\n            </div>\r\n            <strong>Copyright &co" +
"py; 2016 <a");

WriteLiteral(" href=\"javascript:;\"");

WriteLiteral(">衢州普照网络科技有限公司</a></strong>\r\n        </footer>\r\n    </div>\r\n    <!-- ./wrapper -->" +
"\r\n    <!-- jQuery 2.2.3 -->\r\n");

WriteLiteral("    ");

            
            #line 81 "..\..\Views\Shared\_Layout.cshtml"
Write(Scripts.Render(Resources.JQUERY));

            
            #line default
            #line hidden
WriteLiteral("\r\n    <!-- Bootstrap 3.3.6 -->\r\n    <script");

WriteLiteral(" src=\"https://staticfile.qnssl.com/twitter-bootstrap/3.3.5/js/bootstrap.min.js\"");

WriteLiteral("></script>\r\n    <!-- 后台公共Js -->\r\n");

WriteLiteral("    ");

            
            #line 85 "..\..\Views\Shared\_Layout.cshtml"
Write(Scripts.Render(Resources.ADMIN_SCRIPT));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n    <script");

WriteLiteral(" type=\"text/x-handlebars-template\"");

WriteLiteral(" id=\"delete-confirm-template\"");

WriteLiteral(@">
        <div style=""padding: 10px 0px;"">
            <p style=""color: #333; padding-bottom: 10px;"">{{message}}</p>

            <a style=""margin-right: 10px;"" data-ajax=""true"" data-ajax-success=""{{ajaxsuccess}}"" data-ajax-method=""POST"" href=""{{href}}"" class=""btn btn-primary"">
                确定
            </a>

            <button type=""button"" class=""btn btn-default cancel"" onclick=""$(body).click()"">
                取消
            </button>
        </div>
    </script>

");

WriteLiteral("    ");

            
            #line 101 "..\..\Views\Shared\_Layout.cshtml"
Write(RenderSection("scripts", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n</body>\r\n</html>\r\n");

        }
    }
}
#pragma warning restore 1591
