#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using NetSaleSvc.Admin;
    using NetSaleSvc.Admin.Models;
    using NetSaleSvc.Admin.Properties;
    using NetSaleSvc.Entity.Enum;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_SideBar.cshtml")]
    public partial class _Views_Shared__SideBar_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared__SideBar_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\Shared\_SideBar.cshtml"
  
    bool IsAdmin = ViewBag.IsAdmin;
    List<SystemPermissionEnum> CurrentPermissions = ViewBag.CurrentPermissions;

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<!-- 添加新菜单时请注意权限控制：在SystemPermissionEnum中添加新权限，然后在此处进行控制即可 -->\r\n\r\n<aside");

WriteLiteral(" class=\"main-sidebar\"");

WriteLiteral(">\r\n    <!-- sidebar: style can be found in sidebar.less -->\r\n    <section");

WriteLiteral(" class=\"sidebar\"");

WriteLiteral(">\r\n        <!-- sidebar menu: : style can be found in sidebar.less -->\r\n        <" +
"ul");

WriteLiteral(" class=\"sidebar-menu\"");

WriteLiteral(">\r\n            <li");

WriteLiteral(" class=\"header\"");

WriteLiteral(">首页</li>\r\n            <li");

WriteAttribute("class", Tuple.Create(" class=\"", 471), Tuple.Create("\"", 492)
            
            #line 14 "..\..\Views\Shared\_SideBar.cshtml"
, Tuple.Create(Tuple.Create("", 479), Tuple.Create<System.Object, System.Int32>(ViewBag.Home
            
            #line default
            #line hidden
, 479), false)
);

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 496), Tuple.Create("\"", 555)
            
            #line 14 "..\..\Views\Shared\_SideBar.cshtml"
, Tuple.Create(Tuple.Create("", 503), Tuple.Create<System.Object, System.Int32>(Url.Action(MvcNames.Home.Index, MvcNames.Home.Name)
            
            #line default
            #line hidden
, 503), false)
);

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-home\"");

WriteLiteral("></i> <span>首页</span></a></li>\r\n\r\n");

            
            #line 16 "..\..\Views\Shared\_SideBar.cshtml"
            
            
            #line default
            #line hidden
            
            #line 16 "..\..\Views\Shared\_SideBar.cshtml"
             if (IsAdmin 
                || CurrentPermissions.Contains(SystemPermissionEnum.User)
                || CurrentPermissions.Contains(SystemPermissionEnum.Role))
            {

            
            #line default
            #line hidden
WriteLiteral("                <li");

WriteLiteral(" class=\"header\"");

WriteLiteral(">系统管理</li>\r\n");

WriteLiteral("                <li");

WriteAttribute("class", Tuple.Create(" class=\"", 870), Tuple.Create("\"", 902)
            
            #line 21 "..\..\Views\Shared\_SideBar.cshtml"
, Tuple.Create(Tuple.Create("", 878), Tuple.Create<System.Object, System.Int32>(ViewBag.System
            
            #line default
            #line hidden
, 878), false)
, Tuple.Create(Tuple.Create(" ", 893), Tuple.Create("treeview", 894), true)
);

WriteLiteral(">\r\n                    <a");

WriteLiteral(" href=\"javascript:;\"");

WriteLiteral(">\r\n                        <i");

WriteLiteral(" class=\"fa fa-cog\"");

WriteLiteral("></i> <span>系统管理</span>\r\n                        <span");

WriteLiteral(" class=\"pull-right-container\"");

WriteLiteral(">\r\n                            <i");

WriteLiteral(" class=\"fa fa-angle-left pull-right\"");

WriteLiteral("></i>\r\n                        </span>\r\n                    </a>\r\n               " +
"     <ul");

WriteLiteral(" class=\"treeview-menu\"");

WriteLiteral(">\r\n");

            
            #line 29 "..\..\Views\Shared\_SideBar.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 29 "..\..\Views\Shared\_SideBar.cshtml"
                         if (IsAdmin || CurrentPermissions.Contains(SystemPermissionEnum.User))
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <li");

WriteAttribute("class", Tuple.Create(" class=\"", 1416), Tuple.Create("\"", 1437)
            
            #line 31 "..\..\Views\Shared\_SideBar.cshtml"
, Tuple.Create(Tuple.Create("", 1424), Tuple.Create<System.Object, System.Int32>(ViewBag.User
            
            #line default
            #line hidden
, 1424), false)
);

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1441), Tuple.Create("\"", 1500)
            
            #line 31 "..\..\Views\Shared\_SideBar.cshtml"
, Tuple.Create(Tuple.Create("", 1448), Tuple.Create<System.Object, System.Int32>(Url.Action(MvcNames.User.Index, MvcNames.User.Name)
            
            #line default
            #line hidden
, 1448), false)
);

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-user\"");

WriteLiteral("></i>用户管理</a></li>\r\n");

            
            #line 32 "..\..\Views\Shared\_SideBar.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                        ");

            
            #line 33 "..\..\Views\Shared\_SideBar.cshtml"
                         if (IsAdmin || CurrentPermissions.Contains(SystemPermissionEnum.Role))
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <li");

WriteAttribute("class", Tuple.Create(" class=\"", 1725), Tuple.Create("\"", 1746)
            
            #line 35 "..\..\Views\Shared\_SideBar.cshtml"
, Tuple.Create(Tuple.Create("", 1733), Tuple.Create<System.Object, System.Int32>(ViewBag.Role
            
            #line default
            #line hidden
, 1733), false)
);

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1750), Tuple.Create("\"", 1809)
            
            #line 35 "..\..\Views\Shared\_SideBar.cshtml"
, Tuple.Create(Tuple.Create("", 1757), Tuple.Create<System.Object, System.Int32>(Url.Action(MvcNames.Role.Index, MvcNames.Role.Name)
            
            #line default
            #line hidden
, 1757), false)
);

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-group\"");

WriteLiteral("></i>角色管理</a></li>\r\n");

            
            #line 36 "..\..\Views\Shared\_SideBar.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                    </ul>\r\n                </li>\r\n");

            
            #line 39 "..\..\Views\Shared\_SideBar.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 41 "..\..\Views\Shared\_SideBar.cshtml"
            
            
            #line default
            #line hidden
            
            #line 41 "..\..\Views\Shared\_SideBar.cshtml"
             if (IsAdmin || CurrentPermissions.Contains(SystemPermissionEnum.Order))
            {

            
            #line default
            #line hidden
WriteLiteral("                <li");

WriteLiteral(" class=\"header\"");

WriteLiteral(">订单</li>\r\n");

WriteLiteral("                <li");

WriteAttribute("class", Tuple.Create(" class=\"", 2111), Tuple.Create("\"", 2133)
            
            #line 44 "..\..\Views\Shared\_SideBar.cshtml"
, Tuple.Create(Tuple.Create("", 2119), Tuple.Create<System.Object, System.Int32>(ViewBag.Order
            
            #line default
            #line hidden
, 2119), false)
);

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 2137), Tuple.Create("\"", 2221)
            
            #line 44 "..\..\Views\Shared\_SideBar.cshtml"
, Tuple.Create(Tuple.Create("", 2144), Tuple.Create<System.Object, System.Int32>(Url.Action(MvcNames.Order.Index, MvcNames.Order.Name)
            
            #line default
            #line hidden
, 2144), false)
, Tuple.Create(Tuple.Create("", 2198), Tuple.Create("?queries[OrderStatus]=8", 2198), true)
);

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-file-text-o\"");

WriteLiteral("></i> <span>订单管理</span></a></li>\r\n");

            
            #line 45 "..\..\Views\Shared\_SideBar.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </ul>\r\n    </section>\r\n    <!-- /.sidebar -->\r\n</aside>");

        }
    }
}
#pragma warning restore 1591
